# Generated by Django 2.2.3 on 2019-07-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
