# Generated by Django 2.2.3 on 2019-07-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_image_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
    ]
